DROP TABLE MALL_PDT CASCADE CONSTRAINTS; /* 쇼핑몰_상품 */
DROP TABLE MALL_DOG_CATE CASCADE CONSTRAINTS; /* 쇼핑몰_멍 카테 */
DROP TABLE MALL_CAT_CATE CASCADE CONSTRAINTS; /* 쇼핑몰_냥 카테 */
DROP TABLE ORDER_address CASCADE CONSTRAINTS; /* 배송지관리 */
DROP TABLE MALL_DELIVERY CASCADE CONSTRAINTS; /* 배송비종류 */
DROP TABLE MALL_CART CASCADE CONSTRAINTS; /* 쇼핑몰_카트 */


/* 쇼핑몰_멍_카테고리 */
CREATE TABLE MALL_DOG_CATE (
	id NUMBER(12) NOT NULL, /* 멍카테고리아이디 */
	name VARCHAR2(36) NOT NULL /* 분류명 */
)SEGMENT CREATION IMMEDIATE;

CREATE UNIQUE INDEX PK_MALL_DOG_CATE ON MALL_DOG_CATE (id ASC);

ALTER TABLE MALL_DOG_CATE
	ADD CONSTRAINT PK_MALL_DOG_CATE PRIMARY KEY (id);


/* 쇼핑몰_냥_카테고리 */
CREATE TABLE MALL_CAT_CATE (
	id NUMBER(12) NOT NULL, /* 냥카테고리아이디 */
	name VARCHAR2(36) NOT NULL /* 분류명 */
)SEGMENT CREATION IMMEDIATE;

CREATE UNIQUE INDEX PK_MALL_CAT_CATE
	ON MALL_CAT_CATE (id ASC);

ALTER TABLE MALL_CAT_CATE
	ADD CONSTRAINT PK_MALL_CAT_CATE PRIMARY KEY (id);



/* 쇼핑몰_상품 */
CREATE TABLE MALL_PDT (
	id NUMBER(12) NOT NULL, /* 상품아이디 */
	dog_cate NUMBER(12), /* 멍카테고리아이디 */
	cat_cate NUMBER(12), /* 냥카테고리아이디 */
	name VARCHAR2(1500) NOT NULL, /* 상품명 */
	price NUMBER(10) NOT NULL, /* 가격 */
	content VARCHAR2(4000), /* 내용 */
	sale_yn VARCHAR2(1) NOT NULL, /* 판매여부 */
	stock NUMBER(12) NOT NULL, /* 재고 */
	image1 VARCHAR2(255), /* 상품이미지1 */
	image2 VARCHAR2(255), /* 상품이미지2 */
	image3 VARCHAR2(255), /* 상품이미지3 */
	delivery_kind VARCHAR2(1500) NOT NULL, /* 배송비 종류 */
	delivery_condition NUMBER(10), /* 조건 금액 */
	delivery_price NUMBER(10), /* 배송비 */
	regdate DATE DEFAULT SYSDATE /* 등록일시 */
)SEGMENT CREATION IMMEDIATE;

CREATE UNIQUE INDEX PK_MALL_PDT
	ON MALL_PDT (id ASC);

ALTER TABLE MALL_PDT
	ADD CONSTRAINT PK_MALL_PDT PRIMARY KEY (id);


ALTER TABLE MALL_PDT
	ADD CONSTRAINT FK_MALL_DOG_CATE_TO_MALL_PDT FOREIGN KEY (dog_cate ) REFERENCES MALL_DOG_CATE (id);

ALTER TABLE MALL_PDT
	ADD CONSTRAINT FK_MALL_CAT_CATE_TO_MALL_PDT FOREIGN KEY (cat_cate) REFERENCES MALL_CAT_CATE (id);
		

/* 배송지목록 */
CREATE TABLE ORDER_ADDRESS (
	id NUMBER(12) NOT NULL, /* 배송지번호 */
	mem_id VARCHAR2(20) NOT NULL, /* 회원아이디 */
	subject VARCHAR2(36) NOT NULL, /* 배송지명 */
	name VARCHAR2(36) NOT NULL, /* 받는사람 */
	phone VARCHAR2(20) NOT NULL, /* 전화번호 */
	zipcode NUMBER(5) NOT NULL, /* 우편번호 */
	address1 VARCHAR2(255) NOT NULL, /* 주소1 */
	address2 VARCHAR2(255) NOT NULL, /* 주소2 */
	memo VARCHAR2(1500) /* 메모 */
)SEGMENT CREATION IMMEDIATE;

ALTER TABLE ORDER_ADDRESS ADD CONSTRAINT PK_ORDER_ADDRESS PRIMARY KEY (id);	

ALTER TABLE ORDER_ADDRESS
	ADD CONSTRAINT FK_MEMBER_TO_ORDER_ADDRESS FOREIGN KEY (mem_id) REFERENCES MEMBER (id);

/* 쇼핑몰_배송비종류 */
CREATE TABLE MALL_DELIVERY (
	id NUMBER(12) NOT NULL, /* 배송비번호 */
	name VARCHAR2(1500) NOT NULL, /* 배송비유형이름 */
	price NUMBER(10) NOT NULL /* 배송비가격 */
)SEGMENT CREATION IMMEDIATE;

CREATE UNIQUE INDEX PK_MALL_DELIVERY
	ON MALL_DELIVERY (id ASC);

ALTER TABLE MALL_DELIVERY
	ADD CONSTRAINT PK_MALL_DELIVERY PRIMARY KEY (id);
	


/* 쇼핑몰_카트 */
CREATE TABLE MALL_CART (
	id			NUMBER(12) PRIMARY KEY, /* 장바구니 번호 */
	member_id		VARCHAR2(20) NOT NULL, /* 회원아이디 */
	product_id		NUMBER(12) NOT NULL, /* 상품아이디 */
	quantity	NUMBER(4), /* 수량 */
	regdate		 DATE /* 등록일 */
)SEGMENT CREATION IMMEDIATE;

ALTER TABLE MALL_CART
	ADD CONSTRAINT FK_MEMBER_TO_MALL_CART FOREIGN KEY (member_id) REFERENCES MEMBER (id);

ALTER TABLE MALL_CART
	ADD CONSTRAINT FK_MALL_PDT_TO_MALL_CART FOREIGN KEY (product_id) REFERENCES MALL_PDT (id);