DROP SEQUENCE dongne1_seq;
DROP SEQUENCE dongne2_seq;

CREATE SEQUENCE dongne1_seq
START WITH 1 
INCREMENT BY 1
MINVALUE 1;

CREATE SEQUENCE dongne2_seq
START WITH 1 
INCREMENT BY 1
MINVALUE 1;