-- 1.
ALTER TABLE JOONGO_SALE DROP COLUMN sale_state;

-- 2.
ALTER TABLE JOONGO_SALE ADD sale_state varchar2(30) DEFAULT '판매중';



-- 카트
ALTER TABLE MALL_CART
ADD basket_id VARCHAR2(128);

ALTER TABLE MALL_CART
MODIFY member_id VARCHAR2(20) NULL;


-- 주문상태
ALTER TABLE MALL_ORDER_DETAIL 
ADD order_state VARCHAR2(30) DEFAULT '결제완료';


-- 리뷰
ALTER TABLE JOONGO_REVIEW
MODIFY regdate DATE DEFAULT SYSDATE;

ALTER TABLE JOONGO_REVIEW
RENAME COLUMN buy_mem_id TO writer;
SELECT * FROM joongo_review;
SELECT * FROM JOONGO_CHAT jc ;

-- 공지사항
ALTER TABLE NOTICE
ADD writer VARCHAR2(20) NOT NULL;

ALTER TABLE NOTICE
ADD hits NUMBER DEFAULT 0;

-- 주문
ALTER TABLE MALL_ORDER
ADD cancel_price NUMBER(10);