-- 1.
ALTER TABLE JOONGO_SALE DROP COLUMN sale_state;

-- 2.
ALTER TABLE JOONGO_SALE ADD sale_state varchar2(30) DEFAULT '판매중';



-- 카트
ALTER TABLE MALL_CART
ADD basket_id VARCHAR2(128);

ALTER TABLE MALL_CART
MODIFY member_id VARCHAR2(20) NULL;

-- 주문상태
ALTER TABLE MALL_ORDER_DETAIL 
ADD order_state VARCHAR2(30) DEFAULT '결제완료';