-- 1.
ALTER TABLE JOONGO_SALE DROP COLUMN sale_state;

-- 2.
ALTER TABLE JOONGO_SALE ADD sale_state varchar2(30) DEFAULT '판매중';



-- 카트
ALTER TABLE MALL_CART
ADD basket_id VARCHAR2(128);

ALTER TABLE MALL_CART
MODIFY member_id VARCHAR2(20) NULL;


-- 주문상태
ALTER TABLE MALL_ORDER_DETAIL 
ADD order_state VARCHAR2(30) DEFAULT '결제완료';


-- 리뷰
ALTER TABLE JOONGO_REVIEW
MODIFY regdate DATE DEFAULT SYSDATE;

ALTER TABLE JOONGO_REVIEW
RENAME COLUMN buy_mem_id TO writer;

-- 공지사항
ALTER TABLE NOTICE
ADD writer VARCHAR2(20) NOT NULL;

ALTER TABLE NOTICE
ADD hits NUMBER DEFAULT 0;

-- 주문
ALTER TABLE MALL_ORDER
ADD cancel_price NUMBER(10);



-- 2021-03-24
ALTER TABLE JOONGO_REVIEW
RENAME COLUMN buy_mem_id TO writer;

CREATE OR REPLACE VIEW sale_review_view AS
SELECT
	r.ID,
	r.SALE_ID,
	s.MEM_ID AS SALE_MEM_ID,
	s.BUY_MEM_ID AS BUY_MEM_ID,
	r.WRITER AS WRITER_ID,
	mv.NICKNAME AS WRITER_NICKNAME,
	mv.PROFILE_PIC AS WRITER_PROFILE_PIC,
	mv.DONGNE1 AS WRITER_DONGNE1_NAME,
	mv.DONGNE2 AS WRITER_DONGNE2_NAME,
	r.RATING,
	r.CONTENT,
	r.REGDATE
 FROM JOONGO_REVIEW r
  	LEFT OUTER JOIN JOONGO_SALE s ON r.SALE_ID = s.ID
 	LEFT OUTER JOIN MEMBER_VIEW mv ON r.WRITER = mv.ID;